-- Migration: Create audit_logs table and participations logging trigger
BEGIN;

-- 1️⃣ Create the audit_logs table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name text NOT NULL,
  action text NOT NULL,
  record_id text NOT NULL,
  old_data jsonb,
  new_data jsonb,
  changed_by text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2️⃣ Enable RLS on audit_logs
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- 3️⃣ Create RLS Policy for Admins
DROP POLICY IF EXISTS "Admins can view all audit logs" ON public.audit_logs;
CREATE POLICY "Admins can view all audit logs"
  ON public.audit_logs
  FOR SELECT
  TO authenticated
  USING (
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'user_role') = 'admin'
  );

-- 4️⃣ Create trigger function to log changes
CREATE OR REPLACE FUNCTION log_participation_changes()
RETURNS TRIGGER AS $$
DECLARE
  jwt_claims jsonb;
  user_identifier text;
BEGIN
  -- Get current JWT claims if available
  BEGIN
    jwt_claims := current_setting('request.jwt.claims', true)::jsonb;
  EXCEPTION WHEN OTHERS THEN
    jwt_claims := NULL;
  END;

  -- Identify the user who made the change
  user_identifier := coalesce(
    jwt_claims ->> 'username',
    jwt_claims ->> 'email',
    current_user
  );

  -- Insert audit log
  INSERT INTO public.audit_logs (
    table_name,
    action,
    record_id,
    old_data,
    new_data,
    changed_by
  ) VALUES (
    TG_TABLE_NAME,
    TG_OP,
    coalesce(NEW.participation_id::text, OLD.participation_id::text),
    CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN row_to_json(OLD)::jsonb ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN row_to_json(NEW)::jsonb ELSE NULL END,
    user_identifier
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5️⃣ Attach trigger to participations table
DROP TRIGGER IF EXISTS trg_log_participation_changes ON public.participations;
CREATE TRIGGER trg_log_participation_changes
  AFTER INSERT OR UPDATE OR DELETE
  ON public.participations
  FOR EACH ROW
  EXECUTE FUNCTION log_participation_changes();

COMMIT;
